global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@your-domain.com'
  smtp_auth_username: 'your-email@your-domain.com'
  smtp_auth_password: 'your-email-password'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'alert-recipient@your-domain.com'
        send_resolved: true
