global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Use Docker service name instead of IP

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Ensure 'node_exporter' is the service name in Docker Compose

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://54.177.239.162:3030/datasets/ # Use Docker service name instead of IP
        labels:
          instance: marquez_web
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Add configuration for cAdvisor
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: ['alertmanager:9093']


  - job_name: 'marquez-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['54.177.239.162:5000']
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '54.177.239.162:9093'
rule_files:
  - "rules.yml"  # Ensure this file exists with alert rules
