name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - reg
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}  # Specifies the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker-compose push

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets['EC2_SSH_PRIVATE_KEY_' + github.event.inputs.environment.toUpperCase()] }}
          SSH_HOST: ${{ secrets['EC2_HOST_' + github.event.inputs.environment.toUpperCase()] }}
          SSH_USER: ${{ secrets['EC2_USER_' + github.event.inputs.environment.toUpperCase()] }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/marquez
            git pull origin main
            docker-compose pull
            docker-compose up -d
          EOF
